version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - eventservice
  eventservice:
    build:
      context: ./backend/event-service
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cluster0
  mongo:
    image: mongo
    ports:
      - "27017:27017"
